version: "3.9"
services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    ports:
      - "8000:8000"
  proxy:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django
  react:
    build: ./frontend
    container_name: react
    ports:
      - "3000:80"
    depends_on:
      - proxy
      - django
