# Generated by Django 5.0.4 on 2024-05-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logistics",
            name="type",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
