# Generated by Django 5.0.4 on 2024-05-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_logistics_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logistics",
            name="code",
        ),
    ]
